# Generated by Django 2.1.5 on 2019-03-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Base64'), ('image/jpeg;base64', 'JPEG Base64')], default='Plain Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Base64'), ('image/jpeg;base64', 'JPEG Base64')], default='Plain Text', max_length=100),
        ),
    ]
