# Generated by Django 2.1.5 on 2019-03-11 22:08

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190302_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.Image.get_image_dir)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorImage', to='app.Author')),
            ],
        ),
    ]
