# Generated by Django 2.1.5 on 2019-04-02 23:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190329_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.URLField(blank=True, null=True)),
                ('comment', models.TextField(default='')),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Base64'), ('image/jpeg;base64', 'JPEG Base64')], default='Plain Text', max_length=100)),
                ('published', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RemoteCommentPost', to='app.Post')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RemoteServer', to='app.Server')),
            ],
        ),
    ]
