# Generated by Django 2.1.5 on 2019-04-03 03:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remotecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_author', to='app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteFriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RemoteFriend', to='app.Author')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RemoteFriendServer', to='app.Server')),
            ],
        ),
    ]
