# Generated by Django 2.1.5 on 2019-04-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_friendrequest_remotefriend_remotefriendrequest'),
    ]

    operations = [

        migrations.AddField(
            model_name='remotefriend',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_server', to='app.Server'),
        ),
    ]
