# Generated by Django 2.1.5 on 2019-03-13 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190313_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
