# Generated by Django 2.1.5 on 2019-04-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190403_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='app.Author')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='app.Author')),
            ],
        ),
    ]
