# Generated by Django 2.1.5 on 2019-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='visible_to_posts', to='app.Author'),
        ),
    ]
