# Generated by Django 2.1.5 on 2019-04-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_visibleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotefriend',
            name='displayName',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='remotefriend',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotefriend',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotefriendrequest',
            name='displayName',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='remotefriendrequest',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotefriendrequest',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='visibleTo', to='app.Author'),
        ),
        migrations.AlterField(
            model_name='remotefriend',
            name='author',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='no_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='no_posts',
            field=models.BooleanField(default=False),
        ),
    ]
