# Generated by Django 2.1.5 on 2019-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_author_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='private',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('Only me', 'Only me'), ('All friends on my host', 'All friends on my host'), ('All friends', 'All friends'), ('My friends friends', 'My friends friends')], default='Only me', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
