# Generated by Django 2.1.5 on 2019-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190408_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRemoteFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.URLField(blank=True, null=True)),
                ('host', models.URLField(blank=True, null=True)),
                ('displayName', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('friend', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
