# Generated by Django 2.1.5 on 2019-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190313_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('Only me', 'Only me'), ('All friends on my host', 'All friends on my host'), ('All friends', 'All friends'), ('My friends friends', 'My friends friends'), ('Public', 'Public')], default='Only me', max_length=100),
        ),
    ]
