# Generated by Django 2.1.5 on 2019-04-08 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pendingremotefriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingremotefriend',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_remote_server', to='app.Server'),
        ),
    ]
