# Generated by Django 2.1.5 on 2019-04-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pendingremotefriend_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingremotefriend',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.Author'),
        ),
        migrations.AlterField(
            model_name='remotefriend',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_re', to='app.Author'),
        ),
    ]
