# Generated by Django 2.1.5 on 2019-04-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190408_0553'),
        ('app', '0010_auto_20190407_2223'),
    ]

    operations = [
    ]
