# Generated by Django 2.1.5 on 2019-03-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190313_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='bio',
        ),
    ]
