# Generated by Django 2.1.5 on 2019-03-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190318_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_request', to='app.Author')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to='app.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend2',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requester',
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], default='Plain Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SERVERONLY', 'All friends on my host'), ('FRIENDS', 'All friends'), ('FOAF', 'My friends friends'), ('PUBLIC', 'Public')], default='Private', max_length=100),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
